Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1 --tosong=0x1
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2 --tosong=0x2
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3 --tosong=0x3
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x4 --tosong=0x4
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x5 --tosong=0x5
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x6 --tosong=0x6
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x7 --tosong=0x7
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x8 --tosong=0x8
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x9 --tosong=0x9
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xA --tosong=0xA
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xB --tosong=0xB
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xC --tosong=0xC
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xD --tosong=0xD
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xE --tosong=0xE
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xF --tosong=0xF
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x10 --tosong=0x10
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x11 --tosong=0x11
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12 --tosong=0x12
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x13 --tosong=0x13
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x14 --tosong=0x14
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x15 --tosong=0x15
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x16 --tosong=0x16
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x17 --tosong=0x17
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x18 --tosong=0x18
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x19 --tosong=0x19
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1A --tosong=0x1A
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1B --tosong=0x1B
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1C --tosong=0x1C
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1D --tosong=0x1D
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1E --tosong=0x1E
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x1F --tosong=0x1F
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x20 --tosong=0x20
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x21 --tosong=0x21
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x22 --tosong=0x22
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x23 --tosong=0x23
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x24 --tosong=0x24
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x25 --tosong=0x25
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x26 --tosong=0x26
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x27 --tosong=0x27
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x28 --tosong=0x28
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x29 --tosong=0x29
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2A --tosong=0x2A
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2B --tosong=0x2B
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2C --tosong=0x2C
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2D --tosong=0x2D
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2E --tosong=0x2E
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x2F --tosong=0x2F
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x30 --tosong=0x30
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x31 --tosong=0x31
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x32 --tosong=0x32
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x33 --tosong=0x33
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x34 --tosong=0x34
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x35 --tosong=0x35
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x36 --tosong=0x36
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x37 --tosong=0x37
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x38 --tosong=0x38
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x39 --tosong=0x39
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3A --tosong=0x3A
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3B --tosong=0x3B
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3C --tosong=0x3C
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3D --tosong=0x3D
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3E --tosong=0x3E
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x3F --tosong=0x3F
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x40 --tosong=0x40
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x41 --tosong=0x41
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x42 --tosong=0x42
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x43 --tosong=0x43
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x44 --tosong=0x44
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x45 --tosong=0x45
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x46 --tosong=0x46
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x47 --tosong=0x47
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x48 --tosong=0x48
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x49 --tosong=0x49
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x4A --tosong=0x4A
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xE0 --tosong=0x148
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xE1 --tosong=0x149
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xED --tosong=0x1FA
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xEE --tosong=0x1FB
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x104 --tosong=0x104
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x105 --tosong=0x105
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x106 --tosong=0x106
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12A --tosong=0x12A
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12B --tosong=0x12B
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12C --tosong=0x12C
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12D --tosong=0x12D
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12E --tosong=0x12E
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x12F --tosong=0x12F
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0xC6 --tosong=0xC6
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x140 --tosong=0xAD
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x141 --tosong=0x143
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x142 --tosong=0x144
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x143 --tosong=0xBB
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x144 --tosong=0x2BA
Tools\FEBuilderGBA\FEBuilderGBA.exe --rom=myHackWithMusic.gba --songexchange --fromrom=FE6.gba --target=myHackWithMusic.gba --fromsong=0x13F --tosong=0xAE
cd %~dp0EventAssembler
ColorzCore A FE8 -output:%~dp0myHackWithMusic.gba -input:%~dp0Tools\SoundScripts\SoundPriorityFixEA.event --build-times
cd %~dp0