def Funny(i):
    j = hex(i)
    j = j.upper()
    j = j.replace("X", "x")
    return str(j)

names = ["Roy",
         "Marcus",
         "Alen",
         "Lance",
         "Wolt",
         "Bors",
         "Merlinus",
         "Elen",
         "Dieck",
         "Ward",
         "Lot",
         "Shanna",
         "Chad",
         "Lugh",
         "Clarine",
         "Rutger",
         "Saul",
         "Dorothy",
         "Sue",
         "Zelot",
         "Trec",
         "Noah",
         "Astolfo",
         "Lilina",
         "Barthe",
         "Ogier",
         "Gwendolyn",
         "Fir",
         "Sin",
         "Geese",
         "Gonzalez",
         "Klein",
         "Thea",
         "Larum",
         "Elffin",
         "Echidna",
         "Bartre",
         "Raigh",
         "Cath",
         "Melady",
         "Perceval",
         "Cecilia",
         "Sophia",
         "Igrene",
         "Garret",
         "Fae",
         "Hugh",
         "Zeiss",
         "Douglas",
         "Niime",
         "Juno",
         "Dayan",
         "Yoder",
         "Karel",
         "Narcian",
         "Galle",
         "Hector",
         "Brunnya",
         "Murdock",
         "Eliwood",
         "Zephiel",
         "Guinivere",
         "Damas",
         "Ruud",
         "Slater",
         "Erik",
         "Dory",
         "Wagner",
         "Debias",
         "Legance",
         "Henning",
         "Scott",
         "Nord",
         "Zinque",
         "Scollan",
         "Orlo",
         "Roberts",
         "Morgan",
         "Ein",
         "Guerrero",
         "Flaer",
         "Randy",
         "Maggie",
         "Rose",
         "Oates",
         "Raith",
         "Windham",
         "Arcardo",
         "Martel",
         "Monke",
         "Sigune",
         "Kel",
         "Roartz",
         "Tick",
         "SacaeGaidenBosses",
         "Peres",
         "Jahn",
         "IdunnHuman",
         "IdunnDragon",
         "BanditKid",
         "IdunnHood",
         "HectorBlood",
         "HenningRecolor",
         "MartelRecolor1",
         "MonkeRecolor1",
         "MonkeRecolor2",
         "Mordred",
         "MorganRecolor1",
         "MorganRecolor2",
         "OatesRecolor1",
         "OatesRecolor2",
         "PegasusMessanger",
         "Priest",
         "RandyRecolor1",
         "SacaeanVillager",
         "Soldier1",
         "Soldier2",
         "Soldier3",
         "Soldier4",
         "Soldier5",
         "Soldier6",
         "Soldier7",
         "TickRecolor1",
         "TickRecolor2",
         "Villager1",
         "Villager2",
         "Villager3",
         "Villager4",
         "Villager5",
         "Villager6",
         "Villager7",
         "Villager8",
         "Villager9",
         "Villager10",
         "Villager11",
         "Villager12",
         "Villager13",
         "Villager14",
         "Villager15",
         "Villager16",
         "Villager17",
         "Villager18",
         "Villager19",
         "Villager20",
         "Villager21",
         "Villager22",
         "Villager23",
         "Villager24",
         "Villager25",
         "Villager26",
         "Villager27",
         "Villager28",
         "Villager29",
         "Villager30",
         "Villager31",
         "Villager32",
         "Villager33",
         "Villager34",
         "Villager35",
         "Villager36",
         "Villager37",
         "Villager38",
         "Villager39",
         "Villager40",
         "Villager41",
         "Villager42",
         "Villager43",
         "Villager44",
         "Villager45",
         "Villager46",
         "Villager47",
         "Villager48",
         "Villager49",
         "Villager50",
         "Villager51",
         "Villager52",
         "Villager53",
         "Villager54",
         "Villager55",
         "Villager56",
         "Villager57",
         "Villager58",
         "Villager59",
         "Villager60",
         "Villager61",
         "Villager62",
         "WagnerRecolor1",
         "WagnerRecolor2",

]

output = []


i = 1
for name in names:
    output.append("#define "+name+"Mug "+Funny(i)+"\n")
    templateString = [
        "ALIGN 16\n",
        (name+"MugData:\n"),
        ("#incbin \"Dmp/"+name+"_mug.dmp\"\n"),
        ("#incbin \"Dmp/"+name+"_frames.dmp\"\n"),
        ("#incbin \"Dmp/"+name+"_palette.dmp\"\n"),
        ("#incbin \"Dmp/"+name+"_minimug.dmp\"\n"),
        ("setMugEntry("+name+"Mug, "+name+"MugData, 0, 0, 0, 0)\n")]
    for line in templateString:
        output.append(line)
    output.append("\n")
    i += 1
    
with open("GeneratedMugInstaller.event", "w") as writeMugInstaller:
    writeMugInstaller.writelines(output)

#output = []
#
#i = 1
#for name in names:
#    output.append("define "+name+"Mug "+Funny(i)+"\n")
#    i += 1
#
#with open("MugIDs.event", "w") as writeMugIDs:
#    writeMugIDs.writelines(output)