set febCLIPath=Tools\FEBuilderGBA\CLI\FEBuilderGBA.CLI.exe
set fromROMPath=FE6.gba
set targetROMPath=FE6InFE8_Music.gba
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1 --tosong=0x1
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2 --tosong=0x2
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3 --tosong=0x3
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x4 --tosong=0x4
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x5 --tosong=0x5
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x6 --tosong=0x6
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x7 --tosong=0x7
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x8 --tosong=0x8
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x9 --tosong=0x9
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xA --tosong=0xA
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xB --tosong=0xB
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xC --tosong=0xC
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xD --tosong=0xD
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xE --tosong=0xE
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xF --tosong=0xF
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x10 --tosong=0x10
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x11 --tosong=0x11
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12 --tosong=0x12
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x13 --tosong=0x13
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x14 --tosong=0x14
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x15 --tosong=0x15
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x16 --tosong=0x16
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x17 --tosong=0x17
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x18 --tosong=0x18
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x19 --tosong=0x19
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1A --tosong=0x1A
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1B --tosong=0x1B
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1C --tosong=0x1C
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1D --tosong=0x1D
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1E --tosong=0x1E
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x1F --tosong=0x1F
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x20 --tosong=0x20
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x21 --tosong=0x21
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x22 --tosong=0x22
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x23 --tosong=0x23
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x24 --tosong=0x24
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x25 --tosong=0x25
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x26 --tosong=0x26
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x27 --tosong=0x27
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x28 --tosong=0x28
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x29 --tosong=0x29
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2A --tosong=0x2A
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2B --tosong=0x2B
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2C --tosong=0x2C
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2D --tosong=0x2D
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2E --tosong=0x2E
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x2F --tosong=0x2F
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x30 --tosong=0x30
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x31 --tosong=0x31
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x32 --tosong=0x32
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x33 --tosong=0x33
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x34 --tosong=0x34
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x35 --tosong=0x35
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x36 --tosong=0x36
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x37 --tosong=0x37
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x38 --tosong=0x38
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x39 --tosong=0x39
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3A --tosong=0x3A
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3B --tosong=0x3B
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3C --tosong=0x3C
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3D --tosong=0x3D
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3E --tosong=0x3E
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x3F --tosong=0x3F
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x40 --tosong=0x40
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x41 --tosong=0x41
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x42 --tosong=0x42
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x43 --tosong=0x43
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x44 --tosong=0x44
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x45 --tosong=0x45
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x46 --tosong=0x46
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x47 --tosong=0x47
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x48 --tosong=0x48
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x49 --tosong=0x49
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x4A --tosong=0x4A
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xE0 --tosong=0x148
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xE1 --tosong=0x149
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xED --tosong=0x1FA
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xEE --tosong=0x1FB
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x104 --tosong=0x104
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x105 --tosong=0x105
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x106 --tosong=0x106
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12A --tosong=0x12A
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12B --tosong=0x12B
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12C --tosong=0x12C
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12D --tosong=0x12D
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12E --tosong=0x12E
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x12F --tosong=0x12F
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0xC6 --tosong=0xC6
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x140 --tosong=0xAD
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x141 --tosong=0x143
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x142 --tosong=0x144
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x143 --tosong=0xBB
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x144 --tosong=0x2BA
%febCLIPath% --songexchange --rom=%targetROMPath% --fromrom=%fromROMPath% --target=%targetROMPath% --fromsong=0x13F --tosong=0xAE
